import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cfg=window.KETURIO_CONFIG, supabase=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY), $=s=>document.querySelector(s);
const SITE_URL="https://samdiok.github.io/keturio/";
let mode="login",me=null,currentChat=null,currentConversation=null,realtimeChannel=null,typingTimer=null,typingStopTimer=null,remoteTypingTimer=null;
const authScreen=$("#authScreen"),chatApp=$("#chatApp"),authForm=$("#authForm"),authMessage=$("#authMessage"),resendConfirm=$("#resendConfirm"),nameField=$("#nameField"),displayName=$("#displayName"),email=$("#email"),password=$("#password"),authSubmit=$("#authSubmit"),chatList=$("#chatList"),chatWall=$("#chatWall"),input=$("#messageInput"),toast=$("#toast");
function notify(m,error=false){toast.textContent=m;toast.classList.add("show");toast.style.borderColor=error?"rgba(255,113,133,.4)":"";setTimeout(()=>toast.classList.remove("show"),2600)}
function setAuthMode(next){mode=next;$("#loginTab").classList.toggle("active",mode==="login");$("#signupTab").classList.toggle("active",mode==="signup");nameField.classList.toggle("hidden",mode!=="signup");authSubmit.textContent=mode==="login"?"Login":"Create account";authMessage.textContent="";authMessage.classList.remove("error");resendConfirm.classList.add("hidden")}
$("#loginTab").addEventListener("click",()=>setAuthMode("login"));$("#signupTab").addEventListener("click",()=>setAuthMode("signup"));
function showConfirmationMessage(m){authMessage.textContent=m;authMessage.classList.remove("error");resendConfirm.classList.remove("hidden")}
authForm.addEventListener("submit",async e=>{e.preventDefault();authSubmit.disabled=true;authMessage.textContent="Working…";authMessage.classList.remove("error");resendConfirm.classList.add("hidden");try{if(mode==="signup"){const{data,error}=await supabase.auth.signUp({email:email.value.trim(),password:password.value,options:{data:{display_name:displayName.value.trim()||"Keturio User"},emailRedirectTo:SITE_URL}});if(error)throw error;if(!data.session)showConfirmationMessage("Account created. Check your email to confirm your account. You can resend the email below.");else await boot(data.user)}else{const{data,error}=await supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error){if((error.message||"").toLowerCase().includes("confirm"))showConfirmationMessage("Your email is not confirmed yet. Check your inbox or resend the confirmation email.");throw error}await boot(data.user)}}catch(err){if(!authMessage.textContent||authMessage.textContent==="Working…")authMessage.textContent=err.message||"Authentication failed.";authMessage.classList.add("error");if((err.message||"").toLowerCase().includes("confirm"))resendConfirm.classList.remove("hidden")}finally{authSubmit.disabled=false}});
resendConfirm.addEventListener("click",async()=>{const address=email.value.trim();if(!address){authMessage.textContent="Enter your email address first.";authMessage.classList.add("error");return}resendConfirm.disabled=true;authMessage.textContent="Sending confirmation email…";authMessage.classList.remove("error");try{const{error}=await supabase.auth.resend({type:"signup",email:address,options:{emailRedirectTo:SITE_URL}});if(error)throw error;authMessage.textContent="A new confirmation email has been sent. Check your inbox.";resendConfirm.classList.add("hidden");notify("Confirmation email sent.")}catch(err){authMessage.textContent=err.message||"Could not resend the confirmation email.";authMessage.classList.add("error")}finally{resendConfirm.disabled=false}});
async function boot(user){me=user;authScreen.classList.add("hidden");chatApp.classList.remove("hidden");await loadMyProfile();await renderPeople("")}
async function loadMyProfile(){const{data}=await supabase.from("profiles").select("display_name,username").eq("id",me.id).maybeSingle();const name=data?.display_name||me.user_metadata?.display_name||"Keturio User";$("#myName").textContent=name;$("#myEmail").textContent=me.email||"";$("#myAvatar").textContent=name[0]?.toUpperCase()||"K";await supabase.from("profiles").update({last_seen:new Date().toISOString()}).eq("id",me.id)}
async function renderPeople(filter=""){let q=supabase.from("profiles").select("id,display_name,username,last_seen").neq("id",me.id).order("display_name").limit(50);if(filter.trim()){const t=filter.trim().replaceAll(",","");q=q.or(`display_name.ilike.%${t}%,username.ilike.%${t}%`)}const{data,error}=await q;if(error){notify(error.message,true);return}chatList.innerHTML="";if(!data?.length){const empty=document.createElement("div");empty.style.cssText="padding:20px;color:var(--muted);font-size:12px;text-align:center";empty.textContent="No other Keturio users yet. Create another account to test a real chat.";chatList.appendChild(empty);return}data.forEach(person=>{const el=document.createElement("button");el.type="button";el.className="chat-item";const av=document.createElement("div");av.className="avatar gradient";av.textContent=(person.display_name||"K")[0].toUpperCase();const meta=document.createElement("div");meta.className="chat-meta";const strong=document.createElement("strong");strong.textContent=person.display_name||"Keturio User";const span=document.createElement("span");span.textContent=person.username?`@${person.username}`:"Start a conversation";meta.append(strong,span);el.append(av,meta);el.addEventListener("click",()=>openDirectChat(person));chatList.appendChild(el)})}
async function openDirectChat(person){currentChat=person;$("#personName").textContent=person.display_name||"Keturio User";$("#personAvatar").textContent=(person.display_name||"K")[0].toUpperCase();$("#presence").textContent="connecting…";chatApp.classList.add("in-chat");const{data,error}=await supabase.rpc("get_or_create_direct_conversation",{target_user_id:person.id});if(error){notify(error.message,true);$("#presence").textContent="unable to open chat";return}currentConversation=data;$("#presence").textContent="ready";await loadMessages();subscribeToMessages();input.focus()}
async function loadMessages(){chatWall.innerHTML="";const day=document.createElement("div");day.className="day-chip";day.textContent="Conversation";chatWall.appendChild(day);const{data,error}=await supabase.from("messages").select("id,sender_id,content,created_at").eq("conversation_id",currentConversation).order("created_at",{ascending:true}).limit(100);if(error){notify(error.message,true);return}if(!data?.length){showEmptyChat();return}data.forEach(renderMessage);chatWall.scrollTop=chatWall.scrollHeight}
function showEmptyChat(){const note=document.createElement("div");note.className="empty-chat";note.innerHTML="<div class='spark'>✦</div><h2>Say hello</h2><p>Your first message will appear here.</p>";chatWall.appendChild(note)}
function renderMessage(m){const empty=chatWall.querySelector(".empty-chat");if(empty)empty.remove();const row=document.createElement("div");row.className="message"+(m.sender_id===me.id?" mine":"");row.dataset.messageId=m.id;const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=m.content||"";const stamp=document.createElement("span");stamp.className="stamp";stamp.textContent=new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});bubble.appendChild(stamp);row.appendChild(bubble);chatWall.appendChild(row)}
function sendTypingState(isTyping){if(realtimeChannel&&currentConversation)realtimeChannel.send({type:"broadcast",event:"typing",payload:{user_id:me.id,typing:isTyping}})}
function handleLocalTyping(){if(!currentConversation)return;clearTimeout(typingStopTimer);if(input.value.trim()){if(!typingTimer){sendTypingState(true);typingTimer=setTimeout(()=>typingTimer=null,900)}typingStopTimer=setTimeout(()=>{sendTypingState(false);typingTimer=null},1600)}else{sendTypingState(false);typingTimer=null}}
function subscribeToMessages(){if(realtimeChannel)supabase.removeChannel(realtimeChannel);realtimeChannel=supabase.channel(`conversation-${currentConversation}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${currentConversation}`},p=>{if(document.querySelector(`[data-message-id="${p.new.id}"]`))return;renderMessage(p.new);chatWall.scrollTop=chatWall.scrollHeight}).on("broadcast",{event:"typing"},({payload})=>{if(!payload||payload.user_id===me.id)return;clearTimeout(remoteTypingTimer);if(payload.typing){$("#presence").textContent="typing…";remoteTypingTimer=setTimeout(()=>$("#presence").textContent="live",2200)}else $("#presence").textContent="live"}).subscribe(status=>{if(status==="SUBSCRIBED")$("#presence").textContent="live"})}
$("#composer").addEventListener("submit",async e=>{e.preventDefault();if(!currentConversation){notify("Choose a person first.",true);return}const value=input.value.trim();if(!value)return;sendTypingState(false);clearTimeout(typingStopTimer);typingTimer=null;const{data,error}=await supabase.from("messages").insert({conversation_id:currentConversation,sender_id:me.id,content:value,message_type:"text"}).select("id,sender_id,content,created_at").single();if(error){notify(error.message,true);return}input.value="";renderMessage(data);chatWall.scrollTop=chatWall.scrollHeight;input.focus()});
input.addEventListener("input",handleLocalTyping);$("#emojiBtn").addEventListener("click",()=>{input.value+=(input.value?" ":"")+"✨";input.focus();handleLocalTyping()});
$("#backBtn").addEventListener("click",()=>{sendTypingState(false);clearTimeout(typingStopTimer);clearTimeout(remoteTypingTimer);typingTimer=null;chatApp.classList.remove("in-chat");currentChat=null;currentConversation=null;$("#presence").textContent="Choose a person";if(realtimeChannel){supabase.removeChannel(realtimeChannel);realtimeChannel=null}});
$("#searchInput").addEventListener("input",e=>renderPeople(e.target.value));$("#themeBtn").addEventListener("click",()=>document.body.classList.toggle("light"));$("#logoutBtn").addEventListener("click",async()=>{if(realtimeChannel)supabase.removeChannel(realtimeChannel);await supabase.auth.signOut();location.reload()});$("#newChatBtn").addEventListener("click",()=>{$("#searchInput").focus();notify("Search for a Keturio user to start chatting.")});
supabase.auth.onAuthStateChange(async(_,session)=>{if(session?.user&&!me)await boot(session.user)});const{data:{session}}=await supabase.auth.getSession();if(session?.user)await boot(session.user);
